services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app

  customer-service:
    build: ./customer-service
    ports:
      - "8001:8000"
    volumes:
      - ./customer-service:/app

  book-service:
    build: ./book-service
    ports:
      - "8002:8000"
    volumes:
      - ./book-service:/app

  cart-service:
    build: ./cart-service
    ports:
      - "8003:8000"
    volumes:
      - ./cart-service:/app

  staff-service:
    build: ./staff-service
    ports:
      - "8004:8000"
    volumes:
      - ./staff-service:/app

  manager-service:
    build: ./manager-service
    ports:
      - "8005:8000"
    volumes:
      - ./manager-service:/app

  catalog-service:
    build: ./catalog-service
    ports:
      - "8006:8000"
    volumes:
      - ./catalog-service:/app

  order-service:
    build: ./order-service
    ports:
      - "8007:8000"
    volumes:
      - ./order-service:/app

  ship-service:
    build: ./ship-service
    ports:
      - "8008:8000"
    volumes:
      - ./ship-service:/app

  pay-service:
    build: ./pay-service
    ports:
      - "8009:8000"
    volumes:
      - ./pay-service:/app

  comment-rate-service:
    build: ./comment-rate-service
    ports:
      - "8010:8000"
    volumes:
      - ./comment-rate-service:/app

  recommender-ai-service:
    build: ./recommender-ai-service
    ports:
      - "8011:8000"
    volumes:
      - ./recommender-ai-service:/app

volumes:
  postgres_data:
