# Generated by Django 4.2.29 on 2026-03-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shippingmethod'),
        ),
    ]
