# Generated by Django 4.2.29 on 2026-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
